tasks:
  - name: classify_disease_task
    description: >
      Classify images of wheat crops to identify diseases.
      Ensure robustness to varying image quality and conditions.
    expected_output: >
      A list of predictions indicating the disease class for each input image.
    agent: disease_classifier_agent
    tools:
      - DiseaseClassifier
    input:
      image_paths:
        - "src/deseasedetect/images/image (1).jpg"
        - "src/deseasedetect/images/image (2).jpg"
        - "src/deseasedetect/images/image (3).jpg"
        - "src/deseasedetect/images/image (4).jpg"

  - name: enrich_with_info_task
    agent: disease_classifier_agent
    tools:
      - WebsiteSearchTool
    input:
      predictions: "{{classify_disease_task.output.predictions}}"

  - name: "Yolo Object Detection"
    agent: "YoloAgent"
    tools:
      - "YoloPredictionTool"
    input:
      image_paths:
        - "src/new_project/images/image (1).jpg"
        - "src/new_project/images/image (2).jpg"
        - "src/new_project/images/image (3).jpg"
        - "src/new_project/images/image (4).jpg"
